name: Link Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run lychee link checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: >-
            --verbose --no-progress --exclude-mail --max-concurrency 8
            --accept 200,206 --timeout 20s
            ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
